addBasicScreenshotsToClipboard: true
customResolutionPhotoHeight: 2240
customResolutionPhotoWidth: 7680
disableRenderingNetherBedrock: false
isometricPhotoScale: 8
isometricPhotoRotation: 0
isometricPhotoRotationOffset: 0
mirrorIsometricScreenshot: false
