disableServerListIpAddresses: false
disableStatsChecksumVerification: true
enableAuthenticationChanges: false
enableBitDepthFix: false
enableCommandKey: true
enableControlsChanges: false
enableChatChanges: true
enableDeathScreenScoreFix: true
enableDebugGraphChanges: true
enableDebugGraphModernToggle: true
enableDebugMenuWorldSeed: true
enableInventoryChanges: false
enableMojangFixTextOnTitleScreen: false
enableMultiplayerServerChanges: true
enableSkinChanges: false
enableWoodenSignChanges: true
enableQuitButton: false
USE_ALTERNATE_RESOURCES_DOWNLOAD_URL: false
RESOURCES_DOWNLOAD_URL: "http://s3.betacraft.uk:11705/MinecraftResources/"
ALTERNATE_RESOURCES_DOWNLOAD_URL: "http://mcresources.modification-station.net/MinecraftResources/"
renderCape: true
raiseSlimSkinShoulders: false
useResourcesDownloadURL: true
