ADVANCED_HUD_POSITIONS_CONFIG:
  HOTBAR_POSITION_CONFIG:
    enableVisibility: true
    horizontalPosition: 1
    horizontalPositionOffset: 0
    verticalPosition: 0
    verticalPositionOffset: 0
  HEARTS_POSITION_CONFIG:
    enableVisibility: true
    horizontalPosition: 1
    horizontalPositionOffset: 0
    verticalPosition: 0
    verticalPositionOffset: 0
  ARMOR_POSITION_CONFIG:
    enableVisibility: true
    horizontalPosition: 1
    horizontalPositionOffset: 0
    verticalPosition: 0
    verticalPositionOffset: 0
  OXYGEN_POSITION_CONFIG:
    enableVisibility: true
    horizontalPosition: 1
    horizontalPositionOffset: 0
    verticalPosition: 0
    verticalPositionOffset: 0
  OVERLAY_MESSAGE_POSITION_CONFIG:
    enableVisibility: true
    horizontalPosition: 1
    horizontalPositionOffset: 0
    verticalPosition: 0
    verticalPositionOffset: 0
SIMPLE_HUD_POSITION_CONFIG:
  enableVisibility: true
  horizontalPosition: 1
  horizontalPositionOffset: 0
  verticalPosition: 0
  verticalPositionOffset: 0
hudPositioningSystem: 1
putOverlayMessagesBelowHotbar: false
putStatusBarIconsBelowHotbar: false
