# Power Beta defaults
autoWalk=false
boatSteering=false
clickMining=false
fastMinecarts=false
flexible.enabled=false
flexible.overlayColor=0
flexible.overlayOpacity=60
flexible.placeAgainstContainers=false
flexible.showOverlay=true
flexible.showPreview=true
freeLook=false
freeLookFollowThirdPerson=true
freeLookPerspective=FIRST_PERSON
freeLookToggle=false
hotbar.alignment=BOTTOM_RIGHT
hotbar.numberRowKeys=true
hotbar.offsetX=4
hotbar.offsetY=4
hotbar.overlay=true
hotbar.rememberRow=true
hotbar.reverseScroll=false
hotbar.scroll=false
hotbar.selectedRow=2
hotbar.swap=false
placement.attemptsPerTick=2
placement.blacklist=
placement.enabled=false
placement.listMode=BLACKLIST
placement.rememberOrientation=true
placement.restrictionEnabled=false
placement.restrictionMode=FACE
placement.restrictionTiedToFast=true
placement.slabMode=DOUBLE
placement.whitelist=
slabs.announceToggle=true
slabs.enabled=true
sneak.announceToggle=true
sneak.enabled=false
