# Power Beta defaults
blockReach=50
destroySlot=true
doubleTapTicks=7
entityReach=50
flight=true
flightSpeed=100
glide=5
landStopsFlight=true
modePicker=true
shiftClearsInventory=true
showSpectatorSpeed=true
spectatorScroll=true
spectatorScrollStep=10
spectatorSpeed=100
sprintFlight=true
sprintMultiplier=200
sprintToggle=true
