# Power Beta defaults
blockLimit=65536
blocksPerTick=2048
color=0
creativeOnly=true
enabled=false
historySize=20
lineWidth=2
opacity=80
showSelection=true
throughWalls=true
wandEnabled=true
wandItem=271
