bitDepthFix: true
farLandsJitterFix: true
enableSlimeSplitFix: true
nightmarePathfindingFix: true
multiplayerEntityJitterFix: true
boatDismountFix: true
sleepingCameraRotationFix: true
stairsDropFix: true
blockEffectivenessFix: true
pigSaddleDropFix: true
fenceBoundingBoxFix: true
pickBlockFix: true
springPropagationFix: true
lavaWithoutSourceFix: true
liquidBlockDropFix: true
bowHeldFix: true
leggingsWhenRidingFix: true
itemstackRenderingFix: true
fishVelocityFix: true
furnaceConsumeBucketFix: true
armorIconsFix: true
droppedItemSizeFix: true
breakingAnimationFix: true
deathScreenFormattingFix: true
hotbarRenderingFix: true
woodenSlabMiningFix: true
grassBlockItemFix: true
miningDelayFix: true
lastDurabilityFix: true
fenceLightingFix: true
torchBottomFaceFix: true
firstPersonRidingHandFix: true
