fastLeafDecay:
  enableFastLeafDecay: false
  minimumDecayTime: 10
  maximumDecayTime: 25
betterBurning:
  enableBetterBurning: false
  skeletonsBurningArrows: false
  skeletonBurningArrowChance: 70
  burningArrowsSetOnFire: false
  burningEntitySpread: false
  burningEntitySpreadChance: 30
stepAssist: false
moreSounds: false
moreSoundsChests: 2
fallingPipe: false
