sugarCaneOnSand: false
boatsDropThemselves: false
boatsDontBreak: false
pumpkinsPlaceableLikeNormal: false
fencesPlaceableLikeNormal: false
fencesConnectBlocks: false
bookshelvesDropBooks: false
pressurePlatesOnFences: false
shearHarvesting: false
expandChickenHitbox: false
stackableChests: false
modernFlintAndSteel: false
disableSleeping: false
disableSleepSpawning: false
preventItemsStoppingMinecarts: false
allowIgnitingEntities: false
allowTrapdoorsWithoutSupport: false
beta18LeavesRendering: false
