showQuitButton: true
improvedControlsMenu: true
hideAchievementToast: false
achievementBackToMenu: true
disableDebugEntityIdTags: true
frontViewThirdPerson: 0
clearTextFieldWithRightClick: true
fovSlider: true
videoSettingsConfig:
  brightnessSlider: true
  cloudHeightSlider: true
  cloudsToggle: true
  fogDensitySlider: true
  guiScaleSlider: true
  fpsLimitSlider: true
  renderDistanceSlider: true
  vanillaFarValues: false
versionTextConfig:
  showVersionTextIngame: false
  unlicensedCopy: false
  enableCustomVersionText: false
  customVersionText: "Power Beta | Minecraft Beta 1.7.3"
panoramaConfig:
  enablePanorma: false
  blurBackground: true
  panoramaFolder: "glacier"
photoModeConfig:
  enablePhotoModeButton: true
