org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Fabric Properties
	minecraft_version=b1.7.3
	yarn_mappings=b1.7.3+e1fe071
	loader_version=0.19.3

# Mod Properties
	mod_version=0.31.0
	maven_group=net.danygames2014
	archives_base_name=ControlFeatures

    # Access Widener
    accesswidener_name=power_controls

    # Modrinth Publishing
	modrinth_slug=power_controls
	modrinth_version_name=ControlFeatures

# Dependencies
	stapi_version=2.0.0-alpha.6.2
	glass_networking_version=1.0.7
	gcapi_version=3.2.5
	power_recipes_version=1.10.0
	modmenu_version=1.1.1
	#power_creative_inventory_version=0.4.9
	spawneggs_version=1.12.1
	power_commands_version=0.5.10
	retroauth_version=1.1.1
	whatsthis_version=1.2.0
	debugutilities_version=1.0.0