EQUIPMENT_CONFIG:
  bowsHaveDurability: false
  equalizeBaseArmorDurability: false
  modernArmorDefensePoints: false
EXPLOSION_AND_FIRE_CONFIG:
  enableSnowballsExtinguishFire: false
  enableFireTurnsGrassIntoDirt: false
  enableGhastFireballsToInstaKillGhasts: false
  enableDefusingTnt: false
  chanceBlocksDropWhenExploded: 0.3
  disableAllExplosionsBreakingBlocks: false
  disableCreeperExplosionBreakingBlocks: false
  disableGhastExplosionBreakingBlocks: false
  disableGhastExplosionCausingFire: false
  disableLightningStrikeCausingFire: false
  disableTntExplosionBreakingBlocks: false
FLORA_CONFIG:
  enableRandomStickDropFromDeadBushes: false
  enableShearsCollectDeadBush: false
  enableShearsCollectFern: false
  enableShearsCollectTallGrass: false
  appleDropChance: 0.0
  enableLogRotation: false
  enablePlayerPlacedLeafPersistence: false
INTERACTIVE_BLOCK_CONFIG:
  enableChestsOpenWithBlockAbove: false
  enableColorSignsWithDye: false
  enableEditSignsWithFeathers: false
  enableGlueTrapdoorsWithSlimeballs: false
MOB_CONFIG:
  enableZombieDropItem: false
  enableZombiePigmanDropItem: false
  zombieDropItem: 0
  zombiePigmanDropItem: 0
  disableTramplingFarmland: false
  disableTrampleFarmlandWhenBarefoot: false
  disableTrampleFarmlandWithLeatherBoots: false
