plugins { id 'maven-publish'; id 'fabric-loom' version '1.11.8'; id 'babric-loom-extension' version '1.11.9' }

group = 'local.luke'
version = project.mod_version
base.archivesName = 'building-validation'

loom {
    mixin { useLegacyMixinAp = true }
    customMinecraftManifest.set('https://babric.github.io/manifest-polyfill/b1.7.3.json')
    intermediaryUrl.set('https://maven.glass-launcher.net/babric/babric/intermediary/%1$s/intermediary-%1$s-v2.jar')
}

repositories {
    mavenCentral()
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = 'https://maven.glass-launcher.net/babric' }
}

dependencies {
    minecraft 'com.mojang:minecraft:b1.7.3'
    mappings 'babric:barn:b1.7.3+build.8:v2'
    modImplementation files('../build/libs/lpketweaks-1.2.1.jar')
    modImplementation files('../../mc-worldedit-beta/build/libs/worldedit-beta-1.2.1.jar')
    modImplementation 'babric:fabric-loader:0.15.6-babric.2'
    modCompileOnly files('../../mc-lpkecreative/build/libs/lpkecreative-1.1.0.jar')
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand version: project.version }
}

java { withSourcesJar() }
test { useJUnitPlatform() }
tasks.withType(JavaCompile).configureEach { options.release = 17 }
tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

configurations.configureEach {
    resolutionStrategy.eachDependency {
        if (requested.group == 'org.ow2.asm' && requested.name == 'asm-all') useVersion '4.1'
    }
}
