PARTICLES_CONFIG:
  disableAllParticles: false
  disableWaterBubbleParticle: false
  disableFireSmokeParticle: false
  disableNoteParticle: false
  disablePortalParticle: false
  disableExplosionParticle: false
  disableFlameParticle: false
  disableLavaEmberParticle: false
  disableFootstepParticle: false
  disableWaterSplashParticle: false
  disableLargeFireSmokeParticle: false
  disableRedDustParticle: false
  disableSnowballParticle: false
  disableSnowShovelParticle: false
  disableSlimeParticle: false
  disableHeartParticle: false
STACK_SIZE_CONFIG:
  enableModernWoodDoorStackSize: false
  enableModernIronDoorStackSize: false
  enableModernSignStackSize: false
SHOVELS_CONFIG:
  enableShovelsEffectiveOnSoulSand: false
addBiomeToDebugOverlay: true
addDayCounterToDebugOverlay: true
addTotalPlayTimeToDebugOverlay: true
addLightLevelToDebugOverlay: true
addSlimeChunkToDebugOverlay: true
overlayAdditionsYOffset: 0
disableColoredSheepSpawning: false
milkSquids: false
pigsDropBrownMushrooms: false
plantReplacementFixesEnabled: true
slabPlacementFixesEnabled: false
allowCraftingInventorySlots: false
vehicleLogoutLoginFixesEnabled: true
