enableFishingRodLuckOfTheSea: false
enableGoldAppleCureFire: false
enableGoldAxeSilkTouch: false
enableGoldBlockHerobrineSummoner: false
enableGoldBootsSoulSpeed: false
enableGoldChestplateProjectileProtection: false
enableGoldHelmetBlastProtection: false
enableGoldHoeFortune: false
enableGoldLeggingsThorns: false
enableGoldPickaxeSilkTouch: false
enableGoldShovelSilkTouch: false
enableGoldSwordLooting: false
enableSpongeSoaksUpWater: false
